version: '3'
services:

  #PHP Service
  app:
   build:
    context: .
    dockerfile: _docker/php/Dockerfile
   container_name: parser_car_php
   depends_on: 
     - db
   volumes:
     - ./:/var/www/

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: parser_car_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7778:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: parser_car_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped
    tty: true
    ports:
      - "8105:3306"
    environment:
      MYSQL_DATABASE: parser_car
      MYSQL_USER: parser_car
      MYSQL_PASSWORD: parser_car
      MYSQL_ROOT_PASSWORD: parser_car
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./_docker/mysql/data:/var/lib/mysql/
      - ./_docker/mysql/conf/my.cnf:/etc/mysql/my.cnf